    
spring:
    datasource:
        url: jdbc:mariadb://tardygramdb.cbstjjiyw4bi.ap-northeast-2.rds.amazonaws.com:3306/tardygramdb
        driverClassName: org.mariadb.jdbc.Driver
        username: tardygramdb
        password: tardygramdb
    jpa:
        hibernate :
            ddl-auto : update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        
server :
    port : 9000
logging:
  level:
    org.springframework.security: debug
